title: Sri Vishnu Totakura
description: Senior Ruby Engineer, Munich, Germany, Planet Earth
url: https://srivishnu.totakura.in

google_analytics: UA-138258334-1
theme: jekyll-theme-primer

twitter:
  username: tsrivishnu
  card: summary

social:
  name: Sri Vishnu Totakura
  links:
    - https://twitter.com/tsrivishnu
    - https://github.com/tsrivishnu
    - https://www.linkedin.com/in/tsrivishnu/
